### ISSUE TITLE
New Components (5.0.0)

### ISSUE THREAD

**Issue by wbrowar** [wbrowar/WB-Starter#5]
### Utilities
- [x] generic visibility classes, typography helper classes, float classes. form classes
- [x] consistent media queries/mixins
- [ ] responsive embeds
- [x] smooth scrool
- [ ] sticky navigation
- [ ] equalizer
- [ ] data interchange

### Controls
- [ ] switches

### Navigation
- [ ] dropdown menu
- [ ] drilldown menu
- [ ] accordion
- [ ] magellan

### Containers
- [ ] tabs

### Misc
- [x] tooltips
- [ ] badges

**Comment by MarcHartwig13** [comment]
When it comes to making A11y components I found these two references that might be helpful:

[A11y Style Guide](http://a11y-style-guide.com/style-guide/section-forms.html#kssref-forms-checkboxes)
[Salesforce Accessibility](https://www.lightningdesignsystem.com/accessibility/overview/)

**Comment by MarcHartwig13** [comment]
Addition to navigation components:

- Dropdown with possibility to handle multiple levels
- Mega Menu to handle large menu structures (like Bergmann). Maybe coming up with multiple varieties as time goes on.

**Comment by wbrowar** [comment]
Suggestion from Adam Wingate
- [ ] Call to action header

Examples:
- https://ip.com
- https://trello.com
- https://www.hotjar.com

**Comment by wbrowar** [comment]
- [ ] Comparison Charts (like on CBNA)
- [ ] Footers
